import { CssBaseline } from "@mui/material";
import type { Metadata } from "next";
import PostProvider from "./components/PostProvider";
import ShowHeader from "./components/ShowHeader";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CssBaseline/>
        <PostProvider>
          <ShowHeader/>
          {children}
        </PostProvider>
      </body>
    </html>
  );
}
